# Generated by Django 5.2.7 on 2025-10-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclAI', '0002_alter_userprofile_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
