# Generated by Django 5.2.7 on 2025-10-23 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(max_length=50, verbose_name='tipo de material')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade (kg, litros, etc.)')),
                ('observacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações para o coletor')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Coleta'), ('COLETADO', 'Coletado/Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status da coleta')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Gerador')),
            ],
            options={
                'verbose_name': 'Registro de Material',
                'verbose_name_plural': 'Registros de Materiais',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(max_length=15)),
                ('tipo_usuario', models.CharField(choices=[('GERADOR', 'Gerador de Resíduos'), ('RECICLADOR', 'Reciclador')], default='GERADOR', max_length=15, verbose_name='Tipo de Usuário')),
                ('num_moedas', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
