# Generated by Django 5.2.7 on 2025-11-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclAI', '0004_reward_remove_userprofile_user_profile_residue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitada'), ('A', 'Atribuída'), ('E', 'Em rota'), ('C', 'Coletada'), ('N', 'Entregue'), ('F', 'Finalizada'), ('X', 'Cancelada')], default='S', max_length=1),
        ),
    ]
