# Generated by Django 5.2.7 on 2025-11-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclAI', '0008_pointstransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='description',
            field=models.TextField(default='Descrição padrão'),
        ),
        migrations.AddField(
            model_name='reward',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
