# Generated by Django 5.2.7 on 2025-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclAI', '0009_reward_description_reward_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residue',
            name='location',
        ),
        migrations.AddField(
            model_name='collection',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
