# Generated by Django 5.2.7 on 2025-12-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclAI', '0010_remove_residue_location_collection_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Ganho'),
        ),
    ]
